#!/usr/bin/python

import plistlib
import sys
import os

# Make Munki forget about it

installinfoPath = "/Library/Managed Installs/InstallInfo.plist"
installinfo = plistlib.readPlist(installinfoPath)

my_item = 'RepairPermissions'

for item in installinfo.get('optional_installs', []):
    if item['name'] == my_item:
        item['installed'] = False

installinfo = plistlib.writePlist(installinfo, installinfoPath)

SelfServeManifestPath = "/Library/Managed Installs/manifests/SelfServeManifest"

if ( not os.path.isfile(SelfServeManifestPath)):
   d = { 'managed_installs':[''], }
   plistlib.writePlist(d, SelfServeManifestPath)
else:
    print("%s exists." % SelfServeManifestPath)

SelfServeManifest = plistlib.readPlist(SelfServeManifestPath)

for item in SelfServeManifest.get('managed_installs', []):
    if item == my_item:
        SelfServeManifest['managed_installs'].remove(item)

print SelfServeManifest

SelfServeManifest = plistlib.writePlist(SelfServeManifest, SelfServeManifestPath)
sys.exit(0)